param_tracker:
  dim_x: 7
  dim_z: 4
  F: [[1, 0, 0, 0, 1, 0, 0],
      [0, 1, 0, 0, 0, 1, 0],
      [0, 0, 1, 0, 0, 0, 1],
      [0, 0, 0, 1, 0, 0, 0],
      [0, 0, 0, 0, 1, 0, 0],
      [0, 0, 0, 0, 0, 1, 0],
      [0, 0, 0, 0, 0, 0, 1]]
  H: [[1, 0, 0, 0, 0, 0, 0],
      [0, 1, 0, 0, 0, 0, 0],
      [0, 0, 1, 0, 0, 0, 0],
      [0, 0, 0, 1, 0, 0, 0]]
  R: 10.
  P1: 1000.
  P2: 10.
  Q1: 0.01
  Q2: 0.01

param_sort:
  max_age: 1
  min_hits: 3
  iou_threshold: 0.3